[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]

[select]
open_title = "Open with:"

[input]
cd_title = "Change directory:"
create_title = "Create:"
rename_title = "Rename:"
trash_title = "Move to trash:"
delete_title = "Delete:"
find_title = ["Find next:", "Find previous:"]
search_title = "Search:"
shell_title = "Shell:"

[log]
enabled = false
